language: objective-c
osx_image: xcode7.3
xcode_workspace: MNISTKit.xcworkspace
xcode_sdk: iphonesimulator9.2
env:
    global:
    - FRAMEWORK_NAME=MNISTKit
    - IOS_FRAMEWORK_SCHEME="MNISTKit iOS"
    - OSX_FRAMEWORK_SCHEME="MNISTKit OSX"
    matrix:
        - DESTINATION="OS=9.2,name=iPhone 6"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
        - DESTINATION="OS=9.2,name=iPhone 6Ss"        SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
        - DESTINATION="OS=9.3,name=iPhone 6"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
        - DESTINATION="OS=9.3,name=iPhone 6S"         SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
        - DESTINATION="arch=x86_64"                   SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"
script:
    gym --scheme $SCHEME --destination $DESTINATION